eureka:
  instance:
    # 配置注册中心Status显示，否则会出现读取了docker配置中心id，无法读取到配置中心配置 localhost:8991
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # 打开注册中心Status显示修改
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
  client:
    service-url:
      # 注册中心地址
      #defaultZone: http://127.0.0.1:8761/eureka
      defaultZone: http://10.4.237.123:8761/eureka


spring:
  application:
    # 配置中心注册名称
    name: springcloud-config
  cloud:
    config:
      discovery:
        service-id: springcloud-config
        enabled: false
      server:
        git:
#          uri: https://github.com/HLDBanana/springCloud-config
#          username: 949417140@hanergy.com
#          password: 15090667928h
          # 配置中心git仓库地址
          uri: https://git.hanergy.com/independent/config_springcloud.git
          # git用户名
          username: hanlidong@hanergy.com
          # git密码
          password: 15090667928Hh
          #超时时间
          timeout: 5
          #分支
          default-label: master
#      label: master   #master分支
#      profile: dev    #dev环境，和git里的文件名对应
server:
  # 端口
  port: 8991
